name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false 
          submodules: true

      - name: Build
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Reinstall Node.js dependencies
        run: |
          rm -rf node_modules # Remove existing node_modules
          npm ci # Reinstall dependencies for the current platform

      - name: Build project
        run: dotnet publish -c Release -o out

      - name: Check output directory
        run: |
          ls -la out
          ls -la out/wwwroot || echo "No wwwroot directory"
        
      - name: Prepare deployment
        run: |
          # If index.html is in a wwwroot subfolder, copy it to the root
          if [ -f out/wwwroot/index.html ]; then
            cp -r out/wwwroot/* out/
          fi
          # Create a .nojekyll file to prevent GitHub Pages from ignoring files starting with underscore
          touch out/.nojekyll
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out